//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace smallWorld.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int fMemberId { get; set; }
        public string fAccount { get; set; }
        public string fPassword { get; set; }
        public string fName { get; set; }
        public System.DateTime fBirthday { get; set; }
        public string fEmail { get; set; }
        public Nullable<System.DateTime> fBuildtime { get; set; }
        public string fAuthCode { get; set; }
        public int fRole { get; set; }
    }
}
